### ISSUE TITLE
1.13.1, nothing works

### ISSUE THREAD

**Issue by Roy416** [timbru31/SilkSpawnersEcoAddon#14]
## What steps will reproduce the problem?
Few problems. 
#1. Player doesnt get charged or a confirmation when placing or changing spawners. 
#2. A bunch of errors appear in the console, when placing or changing spawners. 
#3. Doesnt take money when placing or changing spawners when it is enabled. 
## Expected output
#1. players get a notification when placing or changing for eco
#2 no errors 
#3 takes money from players

## Log file of the issue/error
https://pastebin.com/evvcAdgn
## /version output?
1.13.1 - 'you are running the latest version'

## SilkSpawners version
6.0.0 snapshot-b489

## SilkSpawnersEcoAddon version

Can't find a version within the plugin :/. But on the jenkins I tried both build #532 and #539

Appreciate the work you're doing <3

**Comment by timbru31** [comment]
Please try https://ci.dustplanet.de/job/SilkSpawnersEcoAddon/540/ - this one works with SilkSpawners v6 (but not with SilkSpawners v5.0.2)
